### ISSUE TITLE
errors in wordpress

### ISSUE THREAD

**Issue by squaremunkey** [davatron5000/FitText.js#49]
Hey, 
I am getting en error in safari
TypeError: 'undefined' is not a function (evaluating '$(window).on('resize', resizer)')

I am getting en error in Firefox
TypeError: $(...).on is not a function
$(window).on('resize', resized);

I am trying to get this to work in wordpress 3.5 using bones theme.

Anyone know why this is happening? Many thanks
